### ISSUE TITLE
Scripts folder missing

### ISSUE THREAD

**Issue by nstar1125** [snuvclab/gtu#1]
Great work!

I'm trying to run a wild video on this project, but I noticed that the repository does not have the 'scripts' folder mentioned in the instruction. 

Is there any way to gain access to this folder?

Thank you.

**Comment by Sulwon-0516** [comment]
Oops. 
I'm sorry. it was my mistake. Now you will be able to check the basic scripts to run. 

Thank you for letting me know and feel free to leave any question.
